### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'kostal'.

### ISSUE THREAD

**Issue by birdie60** [gieljnssns/kostalpiko-sensor-homeassistant#19]
**Describe the bug**
At HA startup, I see an error in the log:
` Logger: homeassistant.loader
Source: loader.py:794
First occurred: 07:49:09 (1 occurrences)
Last logged: 07:49:09
No 'version' key in the manifest file for custom integration 'kostal'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'kostal'`

**Any errors**
```
see above
```

**Config yaml**
```
N/A
```

**Screenshots**
N/A

**Additional context**
Home Assistant 2021.5.3

**Comment by gieljnssns** [comment]
I will archive this custom component since my Kostal inverter is broken and I can not test any changes, you should try https://github.com/rcasula/kostalpiko-homeassistant

**Comment by birdie60** [comment]
OK thank you for your work so far!
Do you know of an active fork of your kostal sensor component?
